const KEY="pp_league_v7_uid",SUPABASE_URL="https://gqlfqoeejgtjpsdvngbh.supabase.co",SUPABASE_KEY="sb_publishable_A26ocTxGPkLry2Y2iBY2mA_kTWNRI4Z",CLOUD_ENDPOINT=`${SUPABASE_URL}/rest/v1/app_state?id=eq.main`;
let state=JSON.parse(localStorage.getItem(KEY)||"null"),currentUserId=localStorage.getItem("pp_user_id")||"";if(!state?.profiles){location.href="index.html"}
const esc=v=>String(v).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));const uid=()=>`u_${Math.random().toString(36).slice(2,8)}${Date.now().toString(36).slice(-4)}`;const me=()=>state.profiles[currentUserId];if(me()?.role!=="admin"){alert("หน้านี้สำหรับ Admin เท่านั้น");location.href="index.html"}
async function cloudRequest(method="GET",body=null){const o={method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}};if(body){o.headers["Content-Type"]="application/json";o.headers.Prefer="return=representation";o.body=JSON.stringify(body)}const r=await fetch(`${CLOUD_ENDPOINT}&select=league,updated_at`,o);if(!r.ok)throw new Error(r.status);return r.json()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));cloudRequest("PATCH",{league:{uidLeague:state},updated_at:new Date().toISOString()}).catch(()=>{})}
function render(){document.getElementById("accounts").innerHTML=Object.values(state.profiles).sort((a,b)=>(b.role==="admin")-(a.role==="admin")||a.displayName.localeCompare(b.displayName,"th")).map(p=>`<div class="account ${p.active===false?"off":""}"><div><strong>${esc(p.displayName)} ${p.role==="admin"?'<span class="badge">ADMIN</span>':""}</strong><small>${p.id} • ${p.active===false?"Inactive":"Active"}</small></div><div class="account-actions"><button class="secondary" data-rename="${p.id}">เปลี่ยนชื่อ</button><button class="blue" data-reset="${p.id}">รีเซ็ต PIN</button><button class="${p.active===false?"primary":"danger"}" data-toggle="${p.id}">${p.active===false?"เปิดใช้งาน":"ปิดใช้งาน"}</button></div></div>`).join("");
 document.querySelectorAll("[data-reset]").forEach(b=>b.onclick=()=>{const p=state.profiles[b.dataset.reset];if(confirm(`รีเซ็ต PIN ของ ${p.displayName} เป็น 1234?`)){p.pin="1234";save();alert("รีเซ็ตแล้ว")}});
 document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const p=state.profiles[b.dataset.toggle];if(p.id===currentUserId&&p.active!==false){alert("ปิดบัญชี Admin ที่กำลังใช้งานไม่ได้");return}p.active=p.active===false?true:false;save();render()});
 document.querySelectorAll("[data-rename]").forEach(b=>b.onclick=()=>{const p=state.profiles[b.dataset.rename],name=prompt("ชื่อใหม่",p.displayName);if(!name?.trim())return;p.displayName=name.trim();save();render()});
}
document.getElementById("create").onclick=()=>{const name=document.getElementById("newName").value.trim(),role=document.getElementById("newRole").value;if(!name)return alert("กรอกชื่อก่อน");if(Object.values(state.profiles).some(p=>p.displayName.toLowerCase()===name.toLowerCase()))return alert("มีชื่อนี้แล้ว");const id=uid();state.profiles[id]={id,displayName:name,pin:"1234",role,active:true,createdAt:new Date().toISOString()};document.getElementById("newName").value="";save();render();alert(`สร้าง ${name} แล้ว • PIN 1234`)}
render();
